### ISSUE TITLE
Créer 15 lignes de données avec INSERT INTO dans la table BATEAU_TYPE

### ISSUE THREAD

**Issue by quentinhoareau** [quentinhoareau/sql_project_mopolo#16]
Référencer les requêtes dans ce fichier (en respectant la convention dans le fichier): https://github.com/quentinhoareau/sql_project_mopolo/blob/main/Insertions_lignes_BoatBooking_Hoareau_Diallo_Aittahar.sql

**Comment by mamadou-mouctar-diallo** [comment]
J'ai inséré quelque ligne mais la liste n'est pas exhaustive du coup l'étendre pour atteindre l'objectif pour 15 lignes

**Comment by quentinhoareau** [comment]
Insérer chaque ligne avec :
INSERT INTO TABLE(champ1,champ2) VALUES (...)

Prendre exemple sur le INSERT INTO BATEAU : https://github.com/quentinhoareau/sql_project_mopolo/blob/main/Insertions_lignes_BoatBooking_Hoareau_Diallo_Aittahar.sql

**Comment by quentinhoareau** [comment]
Le format n'est pas bon. Impossible d'insérer ces lignes. A CORRIGER

![image](https://user-images.githubusercontent.com/64120596/163710094-de3df5be-5c9b-45f2-a4b7-d6d93b479351.png)

**Comment by quentinhoareau** [comment]
J'ai validé, voir les petits correctifs que j'ai apporté à ton code : https://github.com/quentinhoareau/sql_project_mopolo/commit/57b821d92342f6a34d5c7a07523716b071798f19
