### ISSUE TITLE
Créer 15 lignes de données avec INSERT INTO dans la table CLIENT

### ISSUE THREAD

**Issue by quentinhoareau** [quentinhoareau/sql_project_mopolo#17]
Référencer les requêtes dans ce fichier (en respectant la convention dans le fichier): https://github.com/quentinhoareau/sql_project_mopolo/blob/main/Insertions_lignes_BoatBooking_Hoareau_Diallo_Aittahar.sql

**Comment by quentinhoareau** [comment]
- CORRIGER la chaine de caractère : https://github.com/quentinhoareau/sql_project_mopolo/blob/main/Insertions_lignes_BoatBooking_Hoareau_Diallo_Aittahar.sql#L68
____
REMPLACER le `\` par un `'`
**_Bonne façon de faire : 'Rue d''Orsel'_**
_____

**Rappel:** En SQL il faut faire un double quotte pour ignorer la fin de la chaine de caractère et non pas un antislash comme dans un langage banal

**Comment by quentinhoareau** [comment]
Insérer chaque ligne avec :
INSERT INTO TABLE(champ1,champ2) VALUES (...)

Prendre exemple sur le INSERT INTO BATEAU : https://github.com/quentinhoareau/sql_project_mopolo/blob/main/Insertions_lignes_BoatBooking_Hoareau_Diallo_Aittahar.sql

**Comment by an801263** [comment]
C'est terminé et testé
