### ISSUE TITLE
Créer 15 lignes de données avec INSERT INTO dans la table MARQUE

### ISSUE THREAD

**Issue by quentinhoareau** [quentinhoareau/sql_project_mopolo#18]
Référencer les requêtes dans ce fichier (en respectant la convention dans le fichier): https://github.com/quentinhoareau/sql_project_mopolo/blob/main/Insertions_lignes_BoatBooking_Hoareau_Diallo_Aittahar.sql

**IMPORTANT : Ajouter les marques suivantes (voir tous dans le fichier suivant) :** 
![image](https://user-images.githubusercontent.com/64120596/162574181-a91baa37-220b-4e31-8c7d-616757546073.png)

**Comment by mamadou-mouctar-diallo** [comment]
Pour l'instant j'ai pas terminer l'insertion en tenant compte des bateaux du coup je vais revoir en prenant les marque que t'as encadrées.

**Comment by quentinhoareau** [comment]
> Collaborator

D'accord pas de soucis, c'est noté , **pense à bien voir toutes marques dans le fichier et pas seulement celles encadrés**

**Comment by mamadou-mouctar-diallo** [comment]
C'est noté chef

**Comment by quentinhoareau** [comment]
Insérer chaque ligne avec :
INSERT INTO TABLE(champ1,champ2) VALUES (...)

Prendre exemple sur le INSERT INTO BATEAU : https://github.com/quentinhoareau/sql_project_mopolo/blob/main/Insertions_lignes_BoatBooking_Hoareau_Diallo_Aittahar.sql

**Comment by quentinhoareau** [comment]
J'ai validé, voir les petits correctifs que j'ai apporté à ton code : https://github.com/quentinhoareau/sql_project_mopolo/commit/57b821d92342f6a34d5c7a07523716b071798f19
