### ISSUE TITLE
Créer la table  : MARQUE (sql)

### ISSUE THREAD

**Issue by quentinhoareau** [quentinhoareau/sql_project_mopolo#19]
Référencer les requêtes dans ce fichier (en respectant la convention dans le fichier): 
https://github.com/quentinhoareau/sql_project_mopolo/blob/main/Schema_physique_BoatBooking_Hoareau_Diallo_Aittahar.sql

**Comment by quentinhoareau** [comment]
J'ai mis **des feedback sur ton code A CORRIGER** sur ton dernier commit concernant ton CREATE TABLE MARQUE:
https://github.com/quentinhoareau/sql_project_mopolo/commit/f0bf2b754b072206e76baecf2d96fbe6f4ac5e80

**Comment by quentinhoareau** [comment]
Les CHECK sur les premières lettres en majuscule sont manquant sur certains champs.

**Comment by mamadou-mouctar-diallo** [comment]
feedback ok merci de me notifier

**Comment by quentinhoareau** [comment]
J'ai mis  à jours tes noms de CHECK car ton nom : 'CHECK_nom' est utilisé deux fois dans la BDD, ce qui est impossible. Tu utilises le même nom de contraintes pour deux tables différentes (MARQUE et BATEAU_TYPE).

![image](https://user-images.githubusercontent.com/64120596/163774738-a77bb908-8143-4c09-96da-017b2f9b0c60.png)

**Comment by quentinhoareau** [comment]
J'ai vu que tu as pris en compte la remarque du VARCHAR(1000), en revanche c'est possible donc oublions ma remarque , j'ai remis à l'initiale.
