### ISSUE TITLE
Créer la table  : CLIENT (sql)

### ISSUE THREAD

**Issue by quentinhoareau** [quentinhoareau/sql_project_mopolo#20]
Référencer les requêtes dans ce fichier (en respectant la convention dans le fichier): 
https://github.com/quentinhoareau/sql_project_mopolo/blob/main/Schema_physique_BoatBooking_Hoareau_Diallo_Aittahar.sql

**Comment by quentinhoareau** [comment]
**- A VERIFIER** si la contrainte CKC_CL_ADDR_CP_SIZE_CLIENT fonctionne correctement. 
**- A VOIR** si on peut ajouter une contrainte UNIQUE sur le CL_TELEPHONE (si oui ajouter dans le dico des données )
**- AJOUTER** la contrainte : "CL_EMAIL != CL_SECOND_EMAIL" 

Erreur d'exécution de la requête **A CORRIGER** : 

![image](https://user-images.githubusercontent.com/64120596/163569095-a88a918f-d749-40fb-8e1a-7b272cc5390d.png)

**Comment by an801263** [comment]
next => Tester avec l'insertion

**Comment by quentinhoareau** [comment]
CHECK pour "1ere lettre en majuscule" à modifier par :

`CHECK ( colonne= UPPER(SUBSTR(colonne, 1, 1)) || SUBSTR(colonne, 2, LENGTH(colonne)) )`
_"colonne" à remplacer par le nom du champ concerner_

**Comment by an801263** [comment]
c'est terminé, j'ai testé l'insertion des données avec différentes valeurs pour vérifier les contraintes
