### ISSUE TITLE
Requêtes CONSULTATION - 5 requêtes impliquant 2 tables avec jointures internes dont 1 externe + 1 group by + 1 tri

### ISSUE THREAD

**Issue by quentinhoareau** [quentinhoareau/sql_project_mopolo#31]
5 requêtes impliquant 2 tables avec jointures internes dont 1 externe + 1 group by + 1 tri

- [x] Req 1 : @mamadou-mouctar-diallo (Req avec 1 jointure externe)
   - **Description:** ... Pour tous les bateaux afficher le nom/prénom du dernier client réservé ou afficher rien si aucun client (Req avec 1 jointure extrene)
SELECT bat.BT_IMMATRICULE, CL.CL_ID,CL.CL_NOM, CL.CL_PRENOM, RES.RES_DATE_DEBUT
FROM BATEAU bat
LEFT JOIN RESERVATION res ON bat.BT_IMMATRICULE = RES.BT_IMMATRICULE
LEFT JOIN CLIENTELE cl ON cl.CL_ID = res.CL_ID
WHERE res.RES_DATE_DEBUT = (
        SELECT MAX(res2.RES_DATE_DEBUT) 
        FROM RESERVATION res2
        WHERE res2.BT_IMMATRICULE = bat.BT_IMMATRICULE 
) OR res.RES_DATE_DEBUT IS NULL;

- [x] Req 2 : @mamadou-mouctar-diallo 
   - **Description:** Donnez l'immatriculation, le nom, le type de carburant, le type de bateau qui sont de type Yachts et qui ne consomme pas de 'Desiel'.
     SELECT bt.bt_immatricule, bt.bt_nom, bt.bt_type_carburant 
    FROM bateau bt, bateau_type btp
    WHERE bt.btype_id = btp.btype_id
    AND btp.btype_nom = 'Yachts' 
    AND bt.bt_type_carburant != 'Diesel';
- [x] Req 3: @an801263  (Req avec 1 tri)
   - **Description:** La liste des réservations (nom/prénom du client et bateau réservé)trié par date de début de la réservation  (Req avec tri)
   - **SQL :** SELECT c.CL_NOM, c.CL_PRENOM, b.BT_NOM, r.RES_DATE_DEBUT
FROM CLIENTELE c inner join RESERVATION r on r.CL_ID = c.CL_ID inner join BATEAU b on r.BT_IMMATRICULE = b.BT_IMMATRICULE
ORDER BY r.res_date_debut;
- [x] Req 4 : @quentinhoareau (Req avec Group By)
   - **Description:**Nombres de réservation par ville de client depuis toujours  (Req avec Group By)
   - **SQL :** SELECT cli.CL_ADDR_VILLE, COUNT(res.CL_ID) "Nb de réservation"
FROM RESERVATION res
RIGHT JOIN CLIENTELE cli ON cli.CL_ID = res.CL_ID
GROUP BY cli.CL_ADDR_VILLE;

- [x] Req 5 : @quentinhoareau 
   - **Description:** Tous les bateaux qui sont utilisable sur les ports situé à Nice
   - **SQL :** SELECT bat.BT_IMMATRICULE, bat.BT_NOM, prt.prt_addr_ville
FROM BATEAU bat
INNER JOIN PORT prt ON prt.PRT_ID = bat.PRT_ID
WHERE prt.prt_addr_ville = 'Nice';

_PS:  Mettre à jour l'issue au fur à mesure de l'avancé._

**Comment by quentinhoareau** [comment]
@mamadou-mouctar-diallo la requête 1 n'est pas valide 

Tu affiche que les noms des clients, ça dis pas que ce nom là c'est pour le bateau XXXX.
pske là je fais un SELECT CL_NOM, CL_PRENOM FROM CLIENTELE, ça reviens presque au même le résultat.
Affiche moi au moins : l'immatricule du bateau, le dernier client et la date de début de réservation.
Ensuite, il me semble pas qu'il faut un group by, c'est pas nécessaire/
--------------
Voici les étapes pour t'a req :

SELECT [immat. bateau], [nom client] , [prenom client], [nom client], [date debut réservation]
FROM CLIENTELE
INNER JOIN BATEAU ON ...
INNER JOIN RESERVATION ON ...
WHERE [immat. bateau] = (SELECT [max date de debut réservation pour les réservations de l'immat du bateau])

**Comment by mamadou-mouctar-diallo** [comment]
Hello guy je te laisse check quand t'auras le temps req1 @quentinhoareau et laisse moi un commentaire

**Comment by quentinhoareau** [comment]
@mamadou-mouctar-diallo Désolé mais j'ai du mal à comprendre ta req et elle ne donne pas un résultat conforme, suis mes indications ici ci-dessous: 

![image](https://user-images.githubusercontent.com/64120596/165126153-aed23bd8-bbc4-4a09-ad9d-b8b8fc58ab40.png)

**Comment by quentinhoareau** [comment]
Du coup voilà j'ai mis qqe explication , j'ai finalement fais la req 1, je reconnais qu'elle était complexe : 

![image](https://user-images.githubusercontent.com/64120596/165633674-3e4bc4ff-cd5c-4516-8976-79a235d6215f.png)
