### ISSUE TITLE
Requêtes CONSULTATION - 5 requêtes impliquant 1 table dont 1 avec un group By et une avec un Order By

### ISSUE THREAD

**Issue by quentinhoareau** [quentinhoareau/sql_project_mopolo#32]
5 requêtes impliquant 1 table (dont 1 avec un group By et 1 avec un Order By, les 3 autres libres choix)

- [x] Req 1 : @mamadou-mouctar-diallo 
   - **Description:** Savoir toutes les informations du client qui s'appelle 'Lucia'
    SELECT *
    FROM CLIENTELE
    WHERE CL_PRENOM = 'Lucia';
- [x] Req 2 : @mamadou-mouctar-diallo 
   - **Description:** Tous les bateaux qui date avant 1990
    SELECT * 
    FROM Bateau
    WHERE BT_ANNEE < 1990;
- [x] Req 3: @an801263 (Req avec Order By)
   - **Description:** Compter les bateaux par couleur (Req avec Order by)
   - **SQL :** SELECT count(*), BT_COULEUR
FROM BATEAU
GROUP BY BT_COULEUR
ORDER BY BT_COULEUR;
- [x] Req 4 : @quentinhoareau (Req avec Group BY)
   - **Description:** Le nombre total réservation par bateau depuis toujours  (Req avec Group By)
   - **SQL :** SELECT BT_IMMATRICULE, COUNT(*) AS "Nb de réservation"
FROM RESERVATION
GROUP BY BT_IMMATRICULE 
- [x] Req 5 : @quentinhoareau 
   - **Description:** Tous les bateaux qui consomme du 'Diesel' en carburant
   - **SQL :** SELECT BT_IMMATRICULE, BT_TYPE_CARBURANT
FROM BATEAU
WHERE BT_TYPE_CARBURANT = 'Diesel'

_PS:  Mettre à jour l'issue au fur à mesure de l'avancé._

**Comment by mamadou-mouctar-diallo** [comment]
Taches terminees pour moi req 1 and req 2.

**Comment by quentinhoareau** [comment]
> Taches terminees pour moi req 1 and req 2.
Je valide ;)
