### ISSUE TITLE
Requêtes MAJ - 2 requêtes impliquant 2 tables

### ISSUE THREAD

**Issue by quentinhoareau** [quentinhoareau/sql_project_mopolo#34]
2 requêtes impliquant 2 tables

- [x] Req 1 : @quentinhoareau
   - **Description:** On souhaite mettre tous les bateaux situé au port 'Port Nice Carras' non utilisale car ce port est en réparation.
   - **SQL :** UPDATE BATEAU
SET BT_UTILISABLE = 0
WHERE PRT_ID = (SELECT PRT_ID FROM PORT WHERE  prt_nom = 'Port Nice Carras' );
- [x] Req 2 : @mamadou-mouctar-diallo 
   - **Description:** ... Le client Smith Keira veut changer sa date de reservation pour le bateau numero TOR53026 de 15/02/23 09:00:00  a 15/01/23 09:00:00.
   - **SQL :** UPDATE RESERVATION RES
SET RES.RES_DATE_DEBUT = '15/01/23 09:00:00,000000000'
WHERE RES.CL_ID IN ( SELECT CL_ID 
                        FROM CLIENTELE
                        WHERE CL_NOM = 'Smith'
                        AND  CL_PRENOM = 'Keira'
                    )
AND RES.BT_IMMATRICULE = 'TOR53026';

_PS:  Mettre à jour l'issue au fur à mesure de l'avancé._

**Comment by mamadou-mouctar-diallo** [comment]
@quentinhoareau req 2 update traitée je te laisse me faire un feedback

**Comment by quentinhoareau** [comment]
> @quentinhoareau req 2 update traitée je te laisse me faire un feedback

Parfait je valide
