### ISSUE TITLE
Requêtes MAJ - 2 requêtes impliquant 1 table

### ISSUE THREAD

**Issue by quentinhoareau** [quentinhoareau/sql_project_mopolo#35]
2 requêtes impliquant 1 table

- [x] Req 1 : @an801263 
   - **Description:** Jean veut corriger son prénom, il s'est trompé, il a enregistré Aimee à la place de son prénom
   - **SQL :** UPDATE CLIENTELE
SET CL_PRENOM = 'Jean'
WHERE CL_PRENOM = 'Aimee' and CL_NOM = 'Johnson';
- [x] Req 2 : @mamadou-mouctar-diallo 
   - **Description:** Le client Davies Georgina a récemment aménagé sur Nice au 21 rue trachel.
   - **SQL :** UPDATE CLIENTELE
SET CL_ADDR_VILLE = 'Nice', CL_ADDR_CP = '06000', CL_ADDR_RUE = 'Rue Trachel', CL_ADDR_NUM = 21
WHERE CL_NOM = 'Davies'
AND CL_PRENOM = 'Georgina';

_PS:  Mettre à jour l'issue au fur à mesure de l'avancé._

**Comment by quentinhoareau** [comment]
@an801263 la req1 je valide mais modifie le nom de la table dans le code , remplace CLIENT par CLIENTELE

**Comment by mamadou-mouctar-diallo** [comment]
@quentinhoareau req 2 update traitée je te laisse me faire un feedback

**Comment by quentinhoareau** [comment]
> @quentinhoareau req 2 update traitée je te laisse me faire un feedback

Parfait je valide merci
