### ISSUE TITLE
Le dictionnaire de données MERISE

### ISSUE THREAD

**Issue by quentinhoareau** [quentinhoareau/sql_project_mopolo#7]
Titre / description / format des données / type / Indentifiant / contraintes

https://docs.google.com/document/d/13MBhaLNHRpn_0bfM4qUiJE5FKqGBteXoEoqC2Mnqn3o/edit

**Comment by mamadou-mouctar-diallo** [comment]
it's ok @quentinhoareau 
Sorry for the late it's because of work guy. thank you
